<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PAW.Core\PAW2.Core.csproj" />
    <ProjectReference Include="..\PAW.Models\PAW2.Models.csproj" />
    <ProjectReference Include="..\PAW.Repositories\PAW2.Repositories.csproj" />
  </ItemGroup>

</Project>
