<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PAW.Architecture\PAW2.Architecture.csproj" />
    <ProjectReference Include="..\PAW.Data\PAW2.Data.csproj" />
    <ProjectReference Include="..\PAW.Models\PAW2.Models.csproj" />
  </ItemGroup>

</Project>
